apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
spec:
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: shameek/events-event-dev
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: events-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: events-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: event-db-service
            - name: DATABASE_SYNCHRONIZE
              value: "true"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: events-secret
                  key: JWT_SECRET

            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: events-config-map
                  key: NATS_CLUSTER_ID
            - name: NATS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: events-config-map
                  key: NATS_SERVER_URL
            - name: SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_NAME
              value: event

            - name: NODE_ENV
              value: dev

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: events-cloudinary-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: events-cloudinary-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: events-cloudinary-secret
                  key: CLOUDINARY_API_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    app: event
  ports:
    - name: event
      protocol: TCP
      port: 3000
      targetPort: 3000
